### PR TITLE
Remove driverClass

### PR DESCRIPTION
**Pull request by gokulavasan**

### CODE REVIEW

**Comment by bdmogal** [comment]
Also need to update README files.

**Comment by gokulavasan** [comment]
@bdmogal Addressed comment. Please review!

**Comment by bdmogal** [comment]
@gokulavasan There's no mention of `driverClass` anymore. Do you think we should add a line about its existence in the plugin.json or is the following from README.rst sufficient:

"Please find examples of external plugins in the files mysql-connector-java-5.1.35.json and postgresql-9.4.json. Also refer to the CDAP documentation on external plugins for more details."

Otherwise, LGTM :+1:

**Comment by gokulavasan** [comment]
@bdmogal Gave a verbal LGTM. Merging.

**Pull request merged**
